[tool.ruff]
line-length = 120
[tool.ruff.lint]
per-file-ignores = {"tsp_client/__init__.py" = ["F401"]}
[tool.black]
line-length = 120
[tool.isort]
profile = "black"
line_length = 120
skip_gitignore = true
[[tool.mypy.overrides]]
module = "asn1crypto.*"
ignore_missing_imports = true
